name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: none
    needs:
      - check
      - msrv
    steps:
      - run: exit 0

  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2
    - run: |
        cargo check --workspace

  msrv:
    runs-on: ubuntu-latest
    needs: msrv
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: 1.81.0
    - uses: Swatinem/rust-cache@v2
    - run: |
        cargo check --workspace


